### ISSUE TITLE
Using set lightness on color "#ffffff" then using tostring() causes error in AwesomeWM

### ISSUE THREAD

**Issue by oblitzitate** [Firanel/lua-color#4]
When running the following code in AwesomeWM...

```lua
local color = Color("#ffffff")
color:set({lightness = 1})
return color:tostring()
```

...I get the following:

`lua-color/init.lua:832: bad argument #2 to 'format' (number has no integer representation)`

If I use any other color, there doesn't seem to be an issue.

**Comment by Firanel** [comment]
I found the error and will be uploading the fix within 2 days.

The error is caused by a division by zero when calculation saturation with a lightness of one.
