### ISSUE TITLE
Missing source for class function

### ISSUE THREAD

**Issue by Josef-Friedrich** [Firanel/lua-color#6]
I would appreciate it if you could put a link to the class.lua source. Isn't the code from http://lua-users.org/wiki/SimpleLuaClasses?
In my opinion, the comment of the class is also a bit verbose and includes more boilerplate markup than information.

https://github.com/Firanel/lua-color/blob/cf39d567941bbec9579efc2cfdeef0ef8afadaaf/util/class.lua#L1-L19

In this file, I think it was done in an exemplary way.

https://github.com/Firanel/lua-color/blob/cf39d567941bbec9579efc2cfdeef0ef8afadaaf/util/bitwise.lua#L4-L5

**Comment by Firanel** [comment]
It seems to be a slightly modified version of the code at lua-users, though I'm not sure as it is the kind of utility that just gets copied from project to project.

The useless header comment seems to have been added by some editor down the line.

I have added the link and removed the header.

**Comment by Josef-Friedrich** [comment]
Many thanks for the quick handling of the issue.
